export const symptoms = [
  "Fever",
  "Cough",
  "Shortness of breath",
  "Fatigue",
  "Body aches",
  "Headache",
  "Sore throat",
  "Congestion or runny nose",
  "Loss of taste or smell",
  "Nausea or vomiting",
  "Diarrhea",
  "Chills",
  "Muscle pain",
  "Chest pain",
  "Dizziness",
  "Skin rash",
  "Eye redness",
  "Abdominal pain",
  "Swollen lymph nodes",
  "Loss of appetite",
];
